"use client";
import { useEffect, useState } from 'react';
import { Check, Crown, Sparkles } from 'lucide-react';
import { businessPlans } from '@/lib/business-plans';
type Plan = {code:string;name:string;amountToman:number|null;durationDays:number|null;purchasable:boolean;billingPeriod?:'monthly'|'annual';annual?:{amountToman:number|null;durationDays:number;purchasable:boolean}|null};
const errors:Record<string,string>={QUOTE_CHANGED:'قیمت یا مدت تغییر کرده؛ صفحه را تازه کنید و دوباره مبلغ را بررسی کنید.',LOWER_PLAN_ACTIVE:'اشتراک بالاتر شما هنوز فعال است؛ پس از پایان آن می‌توانید اشتراک پایین‌تر بخرید.',INDEFINITE_PLAN_ACTIVE:'همین اشتراک بدون تاریخ پایان برای شما فعال است.',PAYMENT_PROVIDER_NOT_CONFIGURED:'درگاه هنوز فعال نشده است.',PAYMENT_REQUEST_FAILED:'ارتباط با درگاه انجام نشد؛ مبلغی در سایت دریافت نشده است.',CHECKOUT_ALREADY_CREATED:'این درخواست قبلاً ثبت شده؛ سوابق پرداخت را بررسی کنید.',ALREADY_PAID:'پرداخت این درخواست تأیید شده است؛ سوابق را ببینید.'};
export default function BusinessPlanCards(){
  const [current,setCurrent]=useState('free'),[catalog,setCatalog]=useState<Plan[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[selected,setSelected]=useState<Plan|null>(null),[key,setKey]=useState('');
  const [period,setPeriod]=useState<'monthly'|'annual'>('monthly');
  useEffect(()=>{let active=true;Promise.all([fetch('/api/billing/plans',{cache:'no-store'}).then(r=>r.json()),fetch('/api/me/business',{cache:'no-store'}).then(r=>r.json())]).then(([c,p])=>{if(active){setCatalog(c.plans||[]);setCurrent(p.business?.plan?.code||'free');}}).catch(()=>setMessage('دریافت اشتراک‌ها انجام نشد؛ صفحه را دوباره باز کنید.'));return()=>{active=false;};},[]);
  async function pay(){if(!selected||busy)return;setBusy(true);setMessage('');try{const r=await fetch('/api/billing/checkout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({planCode:selected.code,billingPeriod:selected.billingPeriod,expectedAmountToman:selected.amountToman,expectedDurationDays:selected.durationDays,requestKey:key})});const d=await r.json();if(!r.ok||!d.ok)throw Error(errors[d.error]||'ثبت پرداخت انجام نشد؛ پیش از تلاش دوباره، سوابق پرداخت را بررسی کنید.');const url=new URL(d.redirectUrl);if(url.protocol!=='https:'||url.hostname!=='www.zarinpal.com'||!/^\/pg\/StartPay\/A[a-zA-Z0-9]{35}$/.test(url.pathname))throw Error('نشانی درگاه معتبر نیست.');window.location.assign(url.href);}catch(e){setMessage(e instanceof Error?e.message:'اتصال انجام نشد.');}finally{setBusy(false);}}
  return <><p>اشتراک نشان کیفیت یا مهارت نیست و مشتری، رتبه گوگل یا فروش را تضمین نمی‌کند. خرید یک‌باره است؛ درخواست لغو یا بررسی پرداخت از موضوع اشتراک در <a href="/support">پشتیبانی</a> پیگیری می‌شود.</p><div className="billing-period-picker" role="group" aria-label="مدت اشتراک"><button type="button" aria-pressed={period==='monthly'} onClick={()=>{setPeriod('monthly');setSelected(null);}}>۳۰روزه</button><button type="button" aria-pressed={period==='annual'} onClick={()=>{setPeriod('annual');setSelected(null);}}>سالانه · قیمت ۱۰ ماه برای یک سال</button></div><div className="business-plan-grid billing-plan-grid">{businessPlans.map(plan=>{const base=catalog.find(p=>p.code===plan.code);const price=base ? (period==='annual'&&base.annual ? {...base,...base.annual,billingPeriod:'annual' as const} : {...base,billingPeriod:'monthly' as const}) : undefined;return <article className={'business-plan-card '+(plan.code==='pro'?'is-highlighted ':'')+(current===plan.code?'is-current-plan ':'')+'plan-card-'+plan.code} key={plan.code}><img className="billing-plan-image" src={`/images/plans/${plan.code}.webp`} width={1000} height={1000} alt={`معرفی اشتراک ${plan.name}`} loading="lazy"/><span className="business-plan-badge">{plan.code==='premium'?<Crown size={13}/>:<Sparkles size={13}/>} {plan.badge}</span><h2>{plan.name}</h2><strong>{plan.code==='free'?'رایگان':price?.amountToman?`${price.amountToman.toLocaleString('fa-IR')} تومان برای ${price.durationDays?.toLocaleString('fa-IR')} روز`:'قیمت هنوز نهایی نشده'}</strong><p>{plan.description}</p><ul>{plan.features.map(f=><li key={f}><Check size={15}/>{f}</li>)}</ul>{current===plan.code&&<p className="billing-current-plan">اشتراک فعلی شما</p>}{plan.code!=='free'&&<button type="button" className="pill-button" disabled={busy||!price?.purchasable} onClick={()=>{setSelected(price!);setKey(crypto.randomUUID());setMessage('');}}>{price?.purchasable?(current===plan.code?'تمدید اشتراک':'انتخاب و مشاهده مبلغ'):'خرید پس از اتصال درگاه'}</button>}</article>;})}</div>{selected&&<section className="dashboard-panel glass-panel" aria-label="تأیید مبلغ خرید"><h2>{current===selected.code?'تمدید':'خرید'} اشتراک {selected.name}</h2><p>مبلغ نهایی: <b>{selected.amountToman?.toLocaleString('fa-IR')} تومان</b> · مدت: {selected.durationDays?.toLocaleString('fa-IR')} روز</p><p>تمدید همان اشتراک به اعتبار باقی‌مانده اضافه می‌شود. با انتخاب اشتراک بالاتر، مدت جدید از زمان پرداخت شروع می‌شود. این خرید یک‌باره است و برداشت خودکار ندارد.</p><button className="pill-button" type="button" disabled={busy} onClick={()=>void pay()}>{busy?'در حال اتصال…':'تأیید مبلغ و رفتن به درگاه'}</button> <button type="button" disabled={busy} onClick={()=>setSelected(null)}>انصراف</button></section>}<p role="status">{message}</p></>;
}
