"use client";
import {useEffect,useId,useRef,useState} from "react";
import {BUSINESS_CATEGORIES} from "@/lib/business-taxonomy";
import {serviceCatalog} from "@/lib/service-catalog";
const normalize=(value:string)=>value.replace(/ي/g,"ی").replace(/ك/g,"ک").replace(/\u200c/g," ").replace(/\s+/g," ").trim().toLowerCase();
export default function ServiceSearchPicker({services,value,onChange}:{services:string[];value:string;onChange:(value:string)=>void}){
 const id=useId(),root=useRef<HTMLDivElement>(null);
 const [open,setOpen]=useState(false),[expanded,setExpanded]=useState<string|null>(null);
 useEffect(()=>{const close=(event:PointerEvent)=>{if(!root.current?.contains(event.target as Node))setOpen(false);};document.addEventListener("pointerdown",close);return()=>document.removeEventListener("pointerdown",close);},[]);
 const q=normalize(value);
 const groups=BUSINESS_CATEGORIES.map(category=>({label:category.label,items:[...new Set([...category.services,...serviceCatalog.filter(item=>item.category===category.slug).map(item=>item.name)])]}));
 const assigned=new Set(groups.flatMap(group=>group.items));const other=services.filter(service=>!assigned.has(service));if(other.length)groups.push({label:"سایر خدمات غرفه",items:other});
 return <div ref={root} className="service-search-picker" onMouseLeave={()=>{if(window.matchMedia("(hover: hover) and (pointer: fine)").matches)setOpen(false);}} onBlur={event=>{if(!event.currentTarget.contains(event.relatedTarget as Node))setOpen(false);}}><label htmlFor={id}>خدمت موردنیاز</label><input id={id} value={value} placeholder="بنویسید: پرده، مینیمال یا کفپوش…" autoComplete="off" aria-expanded={open} aria-controls={id+"-choices"} onFocus={()=>setOpen(true)} onClick={()=>setOpen(true)} onChange={e=>{onChange(e.target.value);setOpen(true);setExpanded(null);}} onKeyDown={e=>{if(e.key==="Escape")setOpen(false);}}/>{open&&<div id={id+"-choices"} className="service-search-results">{groups.filter(group=>normalize(group.label).includes(q)||group.items.some(item=>normalize(item).includes(q))).map(group=>{const show=expanded===group.label || (!!q&&!normalize(group.label).includes(q));const matches=group.items.filter(item=>!q||normalize(group.label).includes(q)||normalize(item).includes(q));return <div key={group.label}><button type="button" aria-expanded={show} onClick={()=>setExpanded(expanded===group.label?null:group.label)}>{group.label} · انتخاب زیرمجموعه</button>{show&&<div className="service-search-options">{matches.map(item=><button key={item} type="button" onClick={()=>{onChange(item);setOpen(false);}}>{item}</button>)}</div>}</div>;})}{!groups.some(group=>normalize(group.label).includes(q)||group.items.some(item=>normalize(item).includes(q)))&&<p>نتیجه‌ای در فهرست پیدا نشد؛ نیازتان را در توضیح درخواست بنویسید.</p>}<small>انتخاب خدمت، تأیید ارائه آن توسط این غرفه نیست؛ پیش از توافق از غرفه بپرسید.</small><button type="button" onClick={()=>setOpen(false)}>بستن فهرست</button></div>}</div>;
}
