import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { DatabaseSync } from 'node:sqlite';
import { webcrypto } from 'node:crypto';
import vm from 'node:vm';
import ts from 'typescript';
function load(path, imports={}) {
  const exports={};
  vm.runInNewContext(ts.transpileModule(readFileSync(path,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,require:n=>{assert.ok(n in imports,n);return imports[n]},crypto:webcrypto,TextEncoder,Date,Response,Request,URL,AbortSignal,fetch,Uint8Array,console});
  return exports;
}
const schema=load('lib/server/billing-schema.ts'),activation=load('lib/server/billing-activation.ts');
const service=load('lib/server/billing.ts',{'@/lib/business-plans':load('lib/business-plans.ts'),'./billing-schema':schema,'./billing-activation':activation});
const providerModule=load('lib/server/payment-provider.ts');
function fixture(){
  const sql=new DatabaseSync(':memory:');sql.exec(readFileSync('db/schema.sql','utf8'));
  sql.exec("INSERT INTO users(id,full_name,phone) VALUES('owner','Test','09000000000'); INSERT INTO businesses(id,name,slug,status,city) VALUES(1,'Test shop','test','published','Test'),(2,'Other shop','other','published','Test');  INSERT INTO subscriptions(business_id,plan_id,status,starts_at) VALUES(1,1,'active',CURRENT_TIMESTAMP);");
  let chain=Promise.resolve();
  const db={prepare(q){return{values:[],bind(...v){this.values=v;return this},async first(){return sql.prepare(q).get(...this.values)||null},async all(){return{results:sql.prepare(q).all(...this.values)}},async run(){return{meta:{changes:sql.prepare(q).run(...this.values).changes}}}}},batch(stmts){const p=chain.then(async()=>{sql.exec('BEGIN');try{const results=[];for(const s of stmts)results.push(await s.run());sql.exec('COMMIT');return results;}catch(e){sql.exec('ROLLBACK');throw e}});chain=p.catch(()=>{});return p;}};
  const calls=[];let i=0;
  const provider={code:'zarinpal',async request(input){calls.push(input);return{authority:'A'+String(++i).padStart(35,'0'),url:'https://evil.test'}},async verify(authority,amount){calls.push({authority,amount});return{verified:true,reference:authority.slice(1),code:'100'}}};
  const owner={db,business:{id:1},session:{user_id:'owner'}};
  return{sql,db,provider,owner,calls};
}
async function priced(f){await schema.ensureBilling(f.db);f.sql.exec("UPDATE billing_prices SET amount_toman=350000,enabled=1,duration_days=30 WHERE plan_code='premium';UPDATE billing_prices SET amount_toman=200000,enabled=1,duration_days=30 WHERE plan_code='pro';");}
const body=(extra={})=>({planCode:'premium',expectedAmountToman:350000,expectedDurationDays:30,requestKey:webcrypto.randomUUID(),...extra});
test('Prices default to unset; disconnected gateway never creates a financial record',async()=>{const f=fixture();const catalog=await service.billingCatalog(f.db,null);assert.equal(catalog[2].amountToman,null);await priced(f);await assert.rejects(service.createCheckout(f.owner,body(),null),/PAYMENT_PROVIDER_NOT_CONFIGURED/);assert.equal(f.sql.prepare('SELECT COUNT(*) n FROM invoices').get().n,0);});
test('Quote manipulation is rejected, ownership ignored from client, and toman convert to rial exactly once',async()=>{const f=fixture();await priced(f);await assert.rejects(service.createCheckout(f.owner,body({expectedAmountToman:1}),f.provider),/QUOTE_CHANGED/);const r=await service.createCheckout(f.owner,body({amount:1,businessId:2,durationDays:999}),f.provider);assert.equal(f.calls[0].amountRial,3500000);const invoice=f.sql.prepare('SELECT * FROM invoices').get();assert.equal(invoice.business_id,1);assert.equal(invoice.total_amount,350000);assert.equal(invoice.currency,'IRT');assert.match(r.redirectUrl,/^https:\/\/www.zarinpal.com\//);});
test('Changing prices after checkout cannot change charged amount, duration or purchased tier',async()=>{const f=fixture();await priced(f);const r=await service.createCheckout(f.owner,body(),f.provider);f.sql.exec("UPDATE billing_prices SET amount_toman=999999,duration_days=90;");assert.equal(await service.verifyCheckout(f.db,r.id,f.provider),'paid');assert.equal(f.calls[1].amount,3500000);const sub=f.sql.prepare("SELECT p.code,round(julianday(s.ends_at)-julianday('now')) days FROM subscriptions s JOIN plans p ON p.id=s.plan_id WHERE s.status='active'").get();assert.equal(sub.code,'premium');assert.equal(sub.days,30);});
test('Forged success, mismatched authority and stolen checkout without callback secret do not activate',async()=>{const f=fixture();await priced(f);const r=await service.createCheckout(f.owner,body(),f.provider);const cb=new URL(f.calls[0].callbackUrl);for(const extra of [{token:'0'.repeat(64),authority:'A'+'1'.repeat(35)},{token:cb.searchParams.get('token'),authority:'A'+'9'.repeat(35)}])await assert.rejects(service.verifyCheckout(f.db,r.id,f.provider,{...extra,status:'OK'}),/INVALID_CALLBACK/);assert.equal(f.sql.prepare('SELECT COUNT(*) n FROM billing_receipts').get().n,0);f.provider.verify=async()=>({verified:false,code:'-51'});assert.equal(await service.verifyCheckout(f.db,r.id,f.provider,{token:cb.searchParams.get('token'),authority:r.redirectUrl.split('/').pop(),status:'OK'}),'failed');assert.equal(f.sql.prepare("SELECT plan_id FROM subscriptions WHERE status='active'").get().plan_id,1);});
test('Unknown verification and network failure stay pending and can recover without another payment',async()=>{const f=fixture();await priced(f);const r=await service.createCheckout(f.owner,body(),f.provider);const verify=f.provider.verify;f.provider.verify=async()=>{throw Error('offline')};assert.equal(await service.verifyCheckout(f.db,r.id,f.provider),'pending');f.provider.verify=async()=>({verified:false,code:'NaN'});assert.equal(await service.verifyCheckout(f.db,r.id,f.provider),'pending');f.provider.verify=verify;assert.equal(await service.verifyCheckout(f.db,r.id,f.provider),'paid');assert.equal(f.sql.prepare('SELECT COUNT(*) n FROM invoices').get().n,1);});
test('Concurrent callbacks activate once, and same-plan renewal preserves remaining days',async()=>{const f=fixture();await priced(f);f.sql.exec("UPDATE subscriptions SET plan_id=3,ends_at=datetime('now','+20 days')");const r=await service.createCheckout(f.owner,body(),f.provider);await Promise.all([service.verifyCheckout(f.db,r.id,f.provider),service.verifyCheckout(f.db,r.id,f.provider)]);assert.equal(f.sql.prepare("SELECT COUNT(*) n FROM payment_events WHERE event_type='subscription_activated'").get().n,1);assert.equal(f.sql.prepare("SELECT COUNT(*) n FROM subscriptions WHERE status='active'").get().n,1);assert.equal(f.sql.prepare("SELECT round(julianday(ends_at)-julianday('now')) days FROM subscriptions WHERE status='active'").get().days,50);await service.verifyCheckout(f.db,r.id,f.provider);assert.equal(f.sql.prepare("SELECT round(julianday(ends_at)-julianday('now')) days FROM subscriptions WHERE status='active'").get().days,50);});
test('Concurrent retries with the same key issue exactly one gateway request and one invoice',async()=>{const f=fixture();await priced(f);const b=body();const r=await Promise.allSettled([service.createCheckout(f.owner,b,f.provider),service.createCheckout(f.owner,b,f.provider)]);assert.ok(r.some(v=>v.status==='fulfilled'));assert.equal(f.calls.length,1);assert.equal(f.sql.prepare('SELECT COUNT(*) n FROM invoices').get().n,1);assert.equal((await service.createCheckout(f.owner,b,f.provider)).id,r.find(v=>v.status==='fulfilled').value.id);});
test('One gateway receipt cannot activate two invoices; mismatched stored amounts cannot activate',async()=>{const f=fixture();await priced(f);const one=await service.createCheckout(f.owner,body(),f.provider),two=await service.createCheckout(f.owner,body(),f.provider);f.provider.verify=async()=>({verified:true,reference:'1234',code:'100'});await service.verifyCheckout(f.db,one.id,f.provider);await assert.rejects(service.verifyCheckout(f.db,two.id,f.provider),/PAYMENT_NOT_VERIFIED/);assert.equal(f.sql.prepare("SELECT COUNT(*) n FROM payment_events WHERE event_type='subscription_activated'").get().n,1);const three=await service.createCheckout(f.owner,body(),f.provider);f.sql.prepare("UPDATE payments SET amount=1 WHERE id=(SELECT payment_id FROM billing_checkouts WHERE id=?)").run(three.id);await assert.rejects(service.verifyCheckout(f.db,three.id,f.provider),/PAYMENT_AMOUNT_MISMATCH/);});
test('Free plan, lower active tier and indefinite gifts cannot be sold unnecessarily',async()=>{const f=fixture();await priced(f);await assert.rejects(service.createCheckout(f.owner,body({planCode:'free'}),f.provider),/FREE_PLAN/);f.sql.exec("UPDATE subscriptions SET plan_id=3,ends_at=datetime('now','+30 days')");await assert.rejects(service.createCheckout(f.owner,body({planCode:'pro',expectedAmountToman:200000}),f.provider),/LOWER_PLAN_ACTIVE/);f.sql.exec('UPDATE subscriptions SET ends_at=NULL');await assert.rejects(service.createCheckout(f.owner,body(),f.provider),/INDEFINITE_PLAN_ACTIVE/);});
test('Authenticated private history and retries cannot access another business',async()=>{const f=fixture();await priced(f);const r=await service.createCheckout(f.owner,body(),f.provider);assert.equal((await service.billingHistory(f.db,2)).length,0);const imports={'cloudflare:workers':{env:{}},'@/lib/server/business-media':{getOwnedBusiness:async()=>null},'@/lib/server/billing':service,'@/lib/server/payment-provider':providerModule};for(const path of ['checkout','reconcile','history']){const route=load(`app/api/billing/${path}/route.ts`,imports);assert.equal((await(route.POST||route.GET)(new Request('https://www.khonenama.ir/api/billing/'+path,{method:path==='history'?'GET':'POST'}))).status,401);}imports['@/lib/server/business-media'].getOwnedBusiness=async()=>({...f.owner,business:{id:2}});assert.equal((await load('app/api/billing/reconcile/route.ts',imports).POST(new Request('https://www.khonenama.ir/api/billing/reconcile',{method:'POST',body:JSON.stringify({id:r.id})}))).status,404);});
test('Provider is disabled without explicit production config and never accepts fake redirect URLs',async()=>{assert.equal(providerModule.paymentProvider({}),null);assert.equal(providerModule.paymentProvider({PAYMENTS_ENABLED:'true',PAYMENT_PROVIDER:'sandbox',ZARINPAL_MERCHANT_ID:'0'.repeat(36)}),null);const sent=[];const p=providerModule.paymentProvider({PAYMENTS_ENABLED:'true',PAYMENT_PROVIDER:'zarinpal',ZARINPAL_MERCHANT_ID:'11111111-1111-1111-1111-111111111111'},async(url,options)=>{sent.push({url,body:JSON.parse(options.body)});return Response.json({data:url.includes('/request.')?{code:100,authority:'A'+'1'.repeat(35)}:{code:101,ref_id:123}})});assert.ok(p);await p.request({amountRial:3500000,callbackUrl:'https://www.khonenama.ir/api/billing/callback',description:'Test'});assert.equal(sent[0].body.currency,'IRR');assert.equal((await p.verify('A'+'1'.repeat(35),3500000)).verified,true);assert.equal(sent[1].body.amount,3500000);});
test('Only administrator can configure real prices and all changes are audited',async()=>{const f=fixture();const imports={'cloudflare:workers':{env:{DB:f.db}},'@/lib/server/admin-session':{isAdminRequest:async()=>false},'@/lib/server/billing-schema':schema,'@/lib/server/payment-provider':providerModule};let route=load('app/api/admin/billing/route.ts',imports);assert.equal((await route.PATCH(new Request('https://www.khonenama.ir/api/admin/billing',{method:'PATCH'}))).status,401);imports['@/lib/server/admin-session'].isAdminRequest=async()=>true;route=load('app/api/admin/billing/route.ts',imports);const request=b=>new Request('https://www.khonenama.ir/api/admin/billing',{method:'PATCH',body:JSON.stringify(b)});assert.equal((await route.PATCH(request({planCode:'premium',amountToman:350000,durationDays:30,enabled:true}))).status,200);assert.equal((await route.PATCH(request({planCode:'premium',amountToman:1,durationDays:30,enabled:true}))).status,400);assert.equal(f.sql.prepare('SELECT COUNT(*) n FROM billing_price_audit').get().n,1);});
test('Two distinct verified renewals preserve both purchases under concurrent activation',async()=>{const f=fixture();await priced(f);f.sql.exec("UPDATE subscriptions SET plan_id=3,ends_at=datetime('now','+20 days')");const one=await service.createCheckout(f.owner,body(),f.provider),two=await service.createCheckout(f.owner,body(),f.provider);await Promise.all([service.verifyCheckout(f.db,one.id,f.provider),service.verifyCheckout(f.db,two.id,f.provider)]);assert.equal(f.sql.prepare("SELECT round(julianday(ends_at)-julianday('now')) days FROM subscriptions WHERE status='active'").get().days,80);});
test('Late verification of a lower tier never downgrades a currently active higher purchase',async()=>{const f=fixture();await priced(f);const pro=await service.createCheckout(f.owner,body({planCode:'pro',expectedAmountToman:200000}),f.provider),premium=await service.createCheckout(f.owner,body(),f.provider);await service.verifyCheckout(f.db,premium.id,f.provider);await assert.rejects(service.verifyCheckout(f.db,pro.id,f.provider),/PAID_PLAN_CONFLICT/);assert.equal(f.sql.prepare("SELECT plan_id FROM subscriptions WHERE status='active'").get().plan_id,3);assert.equal(f.sql.prepare("SELECT p.status FROM payments p JOIN billing_checkouts c ON c.payment_id=p.id WHERE c.id=?").get(pro.id).status,'verified');});
test('Callback is independent of a browser session, clears its secret and never trusts an arbitrary return URL',async()=>{const f=fixture();await priced(f);const r=await service.createCheckout(f.owner,body(),f.provider);const query=new URL(f.calls[0].callbackUrl);query.searchParams.set('Authority',r.redirectUrl.split('/').pop());query.searchParams.set('Status','OK');query.searchParams.set('returnUrl','https://evil.test');const route=load('app/api/billing/callback/route.ts',{'cloudflare:workers':{env:{DB:f.db}},'@/lib/server/billing':service,'@/lib/server/payment-provider':{paymentProvider:()=>f.provider}});const response=await route.GET(new Request(query));assert.equal(response.status,303);assert.equal(response.headers.get('Location'),'https://www.khonenama.ir/billing/result?status=paid');assert.equal(response.headers.get('Referrer-Policy'),'no-referrer');assert.equal(f.sql.prepare('SELECT status FROM invoices').get().status,'paid');});


